[postgres]
host = "db.bfkzcighzjorhsshlwuc.supabase.co"
database = "postgres"
user = "postgres"
password = "Argarate5988"
port = "5432"  # usually 5432

[supabase]
url = "https://bfkzcighzjorhsshlwuc.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJma3pjaWdoempvcmhzc2hsd3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNDYyNDMsImV4cCI6MjA3ODYyMjI0M30.cM962WWLMNVEQctA14Ib2EcZBIa2_IfvHji1Dh23b9E"